import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Hero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        <div className="h-screen">{children}</div>
        <footer className="bg-orange-500 p-4 rounded mb-5 text-center">
          This is Footer
        </footer>
      </body>
    </html>
  );
}
